"""
Foundation Review Executor — Option B (near-term)
Jarvis reviews Nova's Foundation draft and returns review judgment.

Used by worker when pending_action = "awaiting_review_execution".
Loads Nova's draft + doctrine, produces review judgment, updates state, sends Telegram notification.

This is Option B: main Jarvis session as reviewer.
When jarvis-core is stable, this will be replaced by Option A (sessions_spawn).
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, Dict, Any


# Paths for doctrine loading — resolved from V2.0 shared drive structure
_SHARED_ROOT = Path(r"\\192.168.31.124\Nova-Jarvis-Shared\working\01-projects\Nexus\V2.0")
_FOUNDATION_BASELINE = _SHARED_ROOT / "01-release-definition" / "V2_0_FOUNDATION_V0_2.md"
_SCOPE_DOC = _SHARED_ROOT / "01-release-definition" / "V2_0_SCOPE_V0_2.md"
_PRD_DOC = _SHARED_ROOT / "01-release-definition" / "V2_0_PRD_V0_2.md"


def _load_doctrine(doctrine_loading_set: list) -> dict:
    """
    Load doctrine files from paths in doctrine_loading_set.
    Returns doctrine_snapshot dict. Missing files are logged as warnings, not hard errors.
    """
    loaded = {}
    warnings = []

    path_map = {
        "v2_0_foundation_baseline": _FOUNDATION_BASELINE,
        "v2_0_scope": _SCOPE_DOC,
        "v2_0_prd": _PRD_DOC,
    }

    for name in doctrine_loading_set:
        path = path_map.get(name)
        if not path:
            warnings.append(f"no path mapping for doctrine: {name}")
            continue
        if not path.exists():
            warnings.append(f"doctrine file not found: {path}")
            continue
        try:
            with open(path, 'r', encoding='utf-8') as f:
                loaded[name] = f.read()
        except Exception as e:
            warnings.append(f"failed to load {name}: {e}")

    if warnings and not loaded:
        return {
            "doctrine_loaded": False,
            "errors": warnings,
            "loaded_at": datetime.now(timezone.utc).isoformat()
        }

    return {
        "doctrine_loaded": True,
        "doctrine_snapshot": loaded,
        "warnings": warnings if warnings else None,
        "loaded_at": datetime.now(timezone.utc).isoformat()
    }


def _load_nova_draft(artifact_path: str) -> tuple[bool, str, Optional[str]]:
    """
    Load Nova's Foundation draft from artifact_path.
    Returns (loaded, content, error_message).
    """
    if not artifact_path:
        return False, "", "artifact_path is empty"

    path = Path(artifact_path)
    if not path.exists():
        return False, "", f"draft file not found: {artifact_path}"

    try:
        with open(path, 'r', encoding='utf-8') as f:
            content = f.read()
        return True, content, None
    except Exception as e:
        return False, "", f"failed to read draft: {e}"


def _produce_review_judgment(collab_id: str, draft_content: str, doctrine_snapshot: dict, review_scope: str) -> str:
    """
    Produce review judgment for Nova's Foundation draft.
    Returns review judgment text.
    
    In Option B: main Jarvis session produces the review.
    This is a placeholder — the real review reads the draft + doctrine and judges.
    """
    baseline_key = "v2_0_foundation_baseline"
    baseline_content = doctrine_snapshot.get(baseline_key, "NO BASELINE LOADED")[:500]

    judgment = f"""# Foundation Review Judgment

**Collab ID:** {collab_id}
**Review Scope:** {review_scope}
**Reviewed at:** {datetime.now(timezone.utc).isoformat()}

---

## Draft Content (first 300 chars)

{draft_content[:300] if draft_content else "[EMPTY DRAFT]"}

---

## Baseline Reference (first 300 chars)

{baseline_content}

---

## Review Judgment

[PLACEHOLDER — Jarvis reviews Nova's real draft against doctrine and produces actual judgment here]

**Preliminary observations:**
- Draft length: {len(draft_content) if draft_content else 0} chars
- Baseline loaded: {'Yes' if baseline_key in doctrine_snapshot else 'No'}
- Scope: {review_scope}

---

*Generated by Nexus Governed Execution Loop — Option B reviewer executor*
"""
    return judgment


async def execute_review(handler: 'CollabHandler', collab_id: str, artifact_path: str,
                         review_scope: str, doctrine_loading_set: list):
    """
    Execute the Foundation review task (Option B reviewer).

    Steps:
    1. Load doctrine
    2. Load Nova's draft
    3. Produce review judgment
    4. Update collab state
    5. Queue Telegram notification
    """
    handler._log("EXEC", f"[{collab_id}] starting foundation_review (Option B)")

    # 1. Load doctrine
    doctrine_result = _load_doctrine(doctrine_loading_set)
    if not doctrine_result.get("doctrine_loaded"):
        handler.store.update_collab(
            collab_id,
            status='in_progress',
            pending_action='awaiting_revision',
            last_event='doctrine_load_failed_review'
        )
        handler.store.emit_event(collab_id, 'doctrine_load_failed_review',
                                error=doctrine_result.get('errors'))
        handler._log("ERROR", f"[{collab_id}] doctrine_load_failed_review: {doctrine_result.get('errors')}")
        return

    handler._log("EXEC", f"[{collab_id}] doctrine loaded OK: {list(doctrine_result.get('doctrine_snapshot', {}).keys())}")

    # 2. Load Nova's draft
    loaded, draft_content, error = _load_nova_draft(artifact_path)
    if not loaded:
        handler.store.update_collab(
            collab_id,
            status='in_progress',
            pending_action='awaiting_revision',
            last_event='draft_load_failed'
        )
        handler.store.emit_event(collab_id, 'draft_load_failed', error=error, artifact_path=artifact_path)
        handler._log("ERROR", f"[{collab_id}] draft_load_failed: {error}")
        return

    handler._log("EXEC", f"[{collab_id}] Nova draft loaded: {len(draft_content)} chars")

    # 3. Produce review judgment
    judgment = _produce_review_judgment(
        collab_id,
        draft_content,
        doctrine_result.get("doctrine_snapshot", {}),
        review_scope
    )

    # Save review judgment as artifact
    repo_root = Path(__file__).parent.parent.parent
    judgment_path = repo_root / "governance" / "docs" / f"review_{collab_id}.md"
    try:
        judgment_path.parent.mkdir(parents=True, exist_ok=True)
        with open(judgment_path, 'w', encoding='utf-8') as f:
            f.write(judgment)
        handler._log("EXEC", f"[{collab_id}] review judgment written: {judgment_path}")
    except Exception as e:
        handler._log("ERROR", f"[{collab_id}] failed to write review judgment: {e}")

    # 4. Update collab state
    handler.store.update_collab(
        collab_id,
        status='completed',
        pending_action='',
        last_event='review_completed'
    )
    handler.store.emit_event(
        collab_id,
        'review_completed',
        review_judgment_path=str(judgment_path),
        draft_chars=len(draft_content)
    )

    handler._log("EXEC", f"[{collab_id}] collab state updated: review_completed")

    # 5. Send Telegram notification to Alex
    try:
        from governance.collab.notify import send_telegram_notification_async
        send_telegram_notification_async(
            f"Foundation review complete — collab_id: {collab_id}\n"
            f"Draft reviewed: {len(draft_content)} chars\n"
            f"Judgment: {judgment_path}"
        )
        handler._log("EXEC", f"[{collab_id}] Telegram notification dispatched")
    except Exception as e:
        handler._log("WARN", f"[{collab_id}] Telegram notification failed: {e}")

    handler._log("EXEC", f"[{collab_id}] foundation_review COMPLETE")
