from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    STALE_SOURCE_AUTHORITY = "ERR_STALE_SOURCE_AUTHORITY"
    STALE_EXPECTED_VERSION = "ERR_STALE_EXPECTED_VERSION"
    INVALID_TRANSITION = "ERR_INVALID_TRANSITION"
    MISSING_HUMAN_DECISION = "ERR_MISSING_HUMAN_DECISION"
    MISSING_EVALUATION_PROFILE = "ERR_MISSING_EVALUATION_PROFILE"
    NO_GO_BOUNDARY = "ERR_NO_GO_BOUNDARY"
    ACK_NOT_ACCEPTANCE = "ERR_ACK_NOT_ACCEPTANCE"
    RAW_FEEDBACK_NO_AUTHORITY_MUTATION = "ERR_RAW_FEEDBACK_NO_AUTHORITY_MUTATION"
    MISSING_IDEMPOTENCY_KEY = "ERR_MISSING_IDEMPOTENCY_KEY"
    IDEMPOTENCY_KEY_REUSE = "ERR_IDEMPOTENCY_KEY_REUSE"
    WORKSPACE_MANIFEST_INVALID = "ERR_WORKSPACE_MANIFEST_INVALID"
    WORKSPACE_TEMPLATE_INVALID = "ERR_WORKSPACE_TEMPLATE_INVALID"
    WORKSPACE_COMMAND_INVALID = "ERR_WORKSPACE_COMMAND_INVALID"
    STANDARDIZATION_RECORD_INVALID = "ERR_STANDARDIZATION_RECORD_INVALID"
    STANDARDIZATION_COMMAND_INVALID = "ERR_STANDARDIZATION_COMMAND_INVALID"
    EXECUTION_RECORD_INVALID = "ERR_EXECUTION_RECORD_INVALID"
    EXECUTION_WORKPACKET_INVALID = "ERR_EXECUTION_WORKPACKET_INVALID"
    EXECUTION_COMMAND_INVALID = "ERR_EXECUTION_COMMAND_INVALID"
    DISPATCH_RECORD_INVALID = "ERR_DISPATCH_RECORD_INVALID"
    DISPATCH_COMMAND_INVALID = "ERR_DISPATCH_COMMAND_INVALID"
    DISPATCH_RETURN_INVALID = "ERR_DISPATCH_RETURN_INVALID"
    MONITOR_HITL_RECORD_INVALID = "ERR_MONITOR_HITL_RECORD_INVALID"
    MONITOR_HITL_COMMAND_INVALID = "ERR_MONITOR_HITL_COMMAND_INVALID"


REQUIRED_ERROR_CODES: tuple[ErrorCode, ...] = (
    ErrorCode.STALE_SOURCE_AUTHORITY,
    ErrorCode.STALE_EXPECTED_VERSION,
    ErrorCode.INVALID_TRANSITION,
    ErrorCode.MISSING_HUMAN_DECISION,
    ErrorCode.MISSING_EVALUATION_PROFILE,
    ErrorCode.NO_GO_BOUNDARY,
    ErrorCode.ACK_NOT_ACCEPTANCE,
    ErrorCode.RAW_FEEDBACK_NO_AUTHORITY_MUTATION,
    ErrorCode.WORKSPACE_MANIFEST_INVALID,
    ErrorCode.WORKSPACE_TEMPLATE_INVALID,
    ErrorCode.WORKSPACE_COMMAND_INVALID,
    ErrorCode.STANDARDIZATION_RECORD_INVALID,
    ErrorCode.STANDARDIZATION_COMMAND_INVALID,
    ErrorCode.EXECUTION_RECORD_INVALID,
    ErrorCode.EXECUTION_WORKPACKET_INVALID,
    ErrorCode.EXECUTION_COMMAND_INVALID,
    ErrorCode.DISPATCH_RECORD_INVALID,
    ErrorCode.DISPATCH_COMMAND_INVALID,
    ErrorCode.DISPATCH_RETURN_INVALID,
    ErrorCode.MONITOR_HITL_RECORD_INVALID,
    ErrorCode.MONITOR_HITL_COMMAND_INVALID,
)
